/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly Full 18.0.1.Final (WildFly Core 10.0.3.Final) - 2.0.27.Final
 * Generated at: 2023-06-22 20:28:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;

public final class salaInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <meta http-equiv=\"refresh\" content=\"60\">\n");
      out.write("    <title>Sala Info Page</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            height: 100vh;\n");
      out.write("            background-color: #f2f2f2;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .container {\n");
      out.write("            width: 80%;\n");
      out.write("            max-width: 800px;\n");
      out.write("            background-color: #fff;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 20px;\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .title {\n");
      out.write("            font-size: 28px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .paragraph {\n");
      out.write("            font-size: 18px;\n");
      out.write("            color: #555;\n");
      out.write("            margin: 10px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .separation-line {\n");
      out.write("            margin-top: 20px;\n");
      out.write("            border-top: 1px solid #ccc;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .info {\n");
      out.write("            margin-top: 30px;\n");
      out.write("            font-size: 18px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .info-title {\n");
      out.write("            font-weight: bold;\n");
      out.write("            font-size: 20px;\n");
      out.write("            text-align: center;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 10px 0;\n");
      out.write("            border-top: 1px solid #000;\n");
      out.write("            border-bottom: 1px solid #000;\n");
      out.write("            color: #000;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .info-list {\n");
      out.write("            padding-left: 20px;\n");
      out.write("            list-style-type: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .info-list li:nth-child(odd) {\n");
      out.write("            background-color: #f2f2f2;\n");
      out.write("            padding: 10px 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .lotacao {\n");
      out.write("            font-size: 18px;\n");
      out.write("            position: absolute;\n");
      out.write("            top: 20px;\n");
      out.write("            right: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .bottom-right-section {\n");
      out.write("            margin-top: 20px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: flex-end;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .bottom-right-section input[type=\"text\"] {\n");
      out.write("            padding: 8px;\n");
      out.write("            font-size: 16px;\n");
      out.write("            margin-right: 10px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            border-radius: 4px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .bottom-right-section input[type=\"submit\"] {\n");
      out.write("            padding: 8px 16px;\n");
      out.write("            font-size: 16px;\n");
      out.write("            background-color: #4CAF50;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 4px;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .green {\n");
      out.write("            background: green;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .red {\n");
      out.write("            background: red;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        // Function to change the body color to green for 2 seconds\n");
      out.write("        function Granted() {\n");
      out.write("            document.body.classList.add(\"green\");\n");
      out.write("            setTimeout(function () {\n");
      out.write("                document.body.classList.remove(\"green\");\n");
      out.write("            }, 700);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function Denied() {\n");
      out.write("            document.body.classList.add(\"red\");\n");
      out.write("            setTimeout(function () {\n");
      out.write("                document.body.classList.remove(\"red\");\n");
      out.write("            }, 700);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
 if (session.getAttribute("Response") != null && session.getAttribute("Response").equals("True")) {
    session.setAttribute("Response", "null");

      out.write('\n');

    out.println("<script>Granted();</script>");

      out.write('\n');
 } else if(session.getAttribute("Response") != null && session.getAttribute("Response").equals("False")){
    session.setAttribute("Response", "null");

      out.write('\n');

    out.println("<script>Denied();</script>");

      out.write('\n');
 } 
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <div class=\"lotacao\">Lotação: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.getAttribute(\"Lotacao\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.getAttribute(\"Capacidade\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("    <h1 class=\"title\">Sala ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.getAttribute(\"Codigo\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\n");
      out.write("    <p class=\"paragraph\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.getAttribute(\"Localizacao\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\n");
      out.write("    <div class=\"info\">\n");
      out.write("        <h2 class=\"info-title\">Informação</h2>\n");
      out.write("        <ul class=\"info-list\">\n");
      out.write("            ");

            if (!request.getAttribute("type").equals("null")) {
            
      out.write("\n");
      out.write("            <li>Nome do Evento: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.getAttribute(\"Nome\")}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            ");
 SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
               String inicio = dateFormat.format(new java.util.Date(Long.parseLong((String) request.getAttribute("HoraInicio"))));
               request.setAttribute("inicio", inicio);
               String fim = dateFormat.format(new java.util.Date(Long.parseLong((String) request.getAttribute("HoraFim"))));
               request.setAttribute("fim", fim);
            
      out.write("\n");
      out.write("\n");
      out.write("            <li>Início: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inicio}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            <li>Fim: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fim}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            ");

            if (request.getAttribute("type").equals("Aula")) {
            
      out.write("\n");
      out.write("            <li>Disciplina: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Disciplina}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            <li>Curso: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Curso}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            <li>Docente: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Docente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            <li>Turno: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Turno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            ");

                }else{
            
      out.write("\n");
      out.write("            <li>Orador: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Orador}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            <li>Tema: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Tema}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            <li>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Entrada}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            <li>Descrição: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Descricao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("            ");

                } else {
            
      out.write("\n");
      out.write("            <p>\n");
      out.write("                Sem eventos agendados\n");
      out.write("            </p>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"bottom-right-section\">\n");
      out.write("        <form action=\"\" method=\"post\">\n");
      out.write("            <input type=\"text\" name=\"emailAluno\" placeholder=\"Enter text\">\n");
      out.write("            <input type=\"submit\" value=\"Submit\">\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
